# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(src)			# needed for trace events

# obj-y					+= ion/ — using mtk_ion instead

obj-$(CONFIG_ASHMEM)			+= ashmem.o
obj-$(CONFIG_DEBUG_KINFO)	+= debug_kinfo.o
obj-$(CONFIG_MTK_ION) += mtk_ion/
